enum CalsificationsActionTypeEnum {
    LOAD_CLASIFICATIONS = "LOAD_CLASIFICATIONS",
    FULFILLED_CLASIFICATIONS = "FULFILLED_CLASIFICATIONS",
    INIT_FORM = "INIT_FORM_CLASIFICATION",
    ADD_CLASIFICATION = "ADD_CLASIFICATION"
}

export default CalsificationsActionTypeEnum;