enum CalsificationsActionTypeEnum {
    LOAD_CLASIFICATIONS = "LOAD_CLASIFICATIONS",
    LOAD_CLASIFICATIONS_COMPLETED = "LOAD_CLASIFICATIONS_COMPLETED",
    FULFILLED_CLASIFICATIONS = "FULFILLED_CLASIFICATIONS",
    INIT_FORM = "INIT_FORM_CLASIFICATION",
    ADD_CLASIFICATION = "ADD_CLASIFICATION",
    DELETE_CLASIFICATION = "DELETE_CLASIFICATION"
}

export default CalsificationsActionTypeEnum;