enum ActionsTypesEnum {
    LOAD_COUNTRIES = "LOAD_COUNTRIES",
    FULFILLED_COUNTRIES = "FULFILLED_COUNTRIES",
    ADD_COUNTRY = "ADD_COUNTRY",
    DELETE_COUNTRY = "DELETE_COUNTRY",
    INIT_FORM = "INIT_FORM"
}

export default ActionsTypesEnum;